#!/usr/bin/env ushc

# This is a comment.
echo "1) First line."
if 0 { echo "2) err: if 0 <code> is evaluated." }
if 1 { echo "2) if 1 <code> working well." }
if 0 { } else { echo "3) else working well." }
if 0 { } elseif 1 { echo "4) elseif working well." }

# foreach.
foreach a 1 2 3 4 {
    echo "5) foreach" $a
}

# for.
for {set i 0} {<= $i 2} {set i (+ $i 1)} {
    for {set j 0} {<= $j 2} {set j (+ $j 1)} {
	if (== $i $j) {
	    continue
	}
	echo "5) for" $i $j
    }
}

# while.
set i 0
while {< $i 4} {
    echo "6) while" $i
    set i (+ $i 1)
}

# proc,exec.
proc kaixo {} {
    echo "7) proc,exec:" 1 $1 2 $2
}
exec kaixo a b

# error
# error "8) error, The program should end here"
# echo "E) error not working."
